### CONFIG VLANS & INTERFACES ###

---
- name: Configuration of Interfaces for switches
  hosts: sw-oeste
  connection: local

  tasks:
  
    - name: Register Facts
      ios_facts:

#Force trunking on Interface G0/0 with r-oeste#

    - name: Enable and describe G0/0
      ios_interface:
        authorize: yes
        auth_pass: ansible
        name: G0/0
        description: trunk port with r-oeste

    - name: Enable trunk mode on G0/0
      ios_config:
        authorize: yes
        auth_pass: ansible
        lines:
          - switchport mode trunk
          - switchport trunk encapsulation dot1Q
          - switchport trunk native vlan 1
        parents:
          - interface GigabitEthernet 0/0


####Assign G3/3 to VLAN 21#####

    - name: Enable, describe G3/3
      ios_interface:
        authorize: yes
        auth_pass: ansible
        name: G3/3
        description: Access to Vlan 21
  
    - name: Enable mode access on int G3/3
      ios_config:
        authorize: yes
        auth_pass: ansible
        lines:
          - switchport mode access
          - switchport access vlan 21
        parents:
          - interface GigabitEthernet 3/3

###Assign all other ports as access ports and Shutdown####

    - name: Modo access para las demás interfaces & Shutdown interfaces
      ios_config:
        authorize: yes
        auth_pass: ansible
        lines: 
          - switchport mode access
        parents: 
          - interface range {{ item.name }}
        after:
          - shutdown
      
      with_items:
        - { name: GigabitEthernet 0/1-3 }
        - { name: GigabitEthernet 1/1-3 }
        - { name: GigabitEthernet 2/0-3 }
        - { name: GigabitEthernet 3/0-2 }
    
    - name: Show Running Config
      ios_command:
        authorize: yes
        commands:
          - show run | begin interface

      register: sh_run_interface

    - debug: var=sh_run_interface.stdout_lines
 
    - name: save running to startup when modified
      ios_config:
        authorize: yes
        auth_pass: ansible
        save_when: modified

      when: ansible_net_hostname == "sw-oeste"




